/*
In a real world scenario, this would be a database.
Because this is just an example, I am using JSON.
*/

import { petInfo } from "../types/petInfo";

export const pets: petInfo[] = [
  {
    name: "Joseph",
    image: "images/dog01.jpg",
    bio: "Joseph is an American Staffordshire Terrier.  He loves playing with his tennis ball and getting belly rubs.",
    species: "dog",
    availableForAdoption: true,
    noDogs: true,
    noCats: false,
    noKids: false,
    specialNeeds: false,
  },
  {
    name: "Chubby",
    image: "images/dog02.jpg",
    bio: "Chubby is in need of an exercise partner!  He'd love to come along for a hike or a walk in the park.",
    species: "dog",
    availableForAdoption: true,
    noDogs: true,
    noCats: true,
    noKids: true,
    specialNeeds: false,
  },
  {
    name: "Lola",
    image: "images/dog03.jpg",
    bio: "Lola is a strong, independent woman who'd really like a home to own!  She's deaf, but very friendly with people and other animals.",
    species: "dog",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: true,
  },
  {
    name: "Fluffy",
    image: "images/dog04.jpg",
    bio: "Fluffy is a lap dog.  She is the perfect companion for a retired couple, or a family that wants a snuggle buddy.",
    species: "dog",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: false,
  },
  {
    name: "Kitty",
    image: "images/cat01.jpg",
    bio: "Kitty is a dog-like cat.  She wants to be pet all the time, and enjoys watching TV with her human.",
    species: "cat",
    availableForAdoption: true,
    noDogs: true,
    noCats: false,
    noKids: false,
    specialNeeds: false,
  },
  {
    name: "Tank",
    image: "images/cat02.jpg",
    bio: "Tank is in need of an exercise partner!  He'd love to come along for a hike or a walk in the park.",
    species: "cat",
    availableForAdoption: true,
    noDogs: true,
    noCats: true,
    noKids: true,
    specialNeeds: false,
  },
  {
    name: "Momma",
    image: "images/cat03.jpg",
    bio: "Momma is a strong, independent woman who'd really like a home to own!  She's deaf, but very friendly with people and other animals.",
    species: "cat",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: true,
  },
  {
    name: "FooFoo",
    image: "images/cat04.png",
    bio: "FooFoo is super soft, and not afraid of anything!  She'd be good in a home with children.",
    species: "cat",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: false,
  },
  {
    name: "DigDig",
    image: "images/bunny01.jpg",
    bio: "DigDig loves digging!  He's blind so \"keep an eye on him\" when he's outside of his cage.",
    species: "bunny",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: true,
  },
  {
    name: "Babs and Buster",
    image: "images/bunny02.jpg",
    bio: "Babs and Buster are friendly rabbits.  They are inseperable!",
    species: "bunny",
    availableForAdoption: true,
    noDogs: true,
    noCats: true,
    noKids: false,
    specialNeeds: false,
  },
  {
    name: "HamHam",
    image: "images/hamster01.jpg",
    bio: "HamHam is super soft, and not afraid of anything!  He'd be good in a home with children.",
    species: "hamster",
    availableForAdoption: true,
    noDogs: false,
    noCats: false,
    noKids: false,
    specialNeeds: false,
  },
];
